<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use DateTime;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert(
        [
            ['name' => "ディストレストレザージャケット",'price' => 275000,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックのジャケット。かすかにダメージ加工の施されたレザーを使用。胸元にブランドの刻印がされたレザーパッチのディテール。センターでフロントジッパー開閉、プルとカフスのついたフロントポケットのディテール。ヘムのサイドはバックルで調節可能。ヒップ丈、フィット感のあるデザイン。','gender' => 'メンズ'], 
            ['name' => "ルーズフィットデニムジャケット",'price' => 72600,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのライトブルーデニムジャケット。長めの袖と丈を配したルーズフィットスタイル。コットンのリジッドデニムを使用。','gender' => 'メンズ'], 
            ['name' => "コットンブレンドオーバーシャツ",'price' => 73700,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのオーバーシャツ。エレクトリックパープルの色合いでツイルコットンブレンド素材を使用。フロントセンターにリングスナップ留め、背面にスナップボタンを備えた調節可能なタブ付き。サイドポケット、胸元と袖にパッチポケットを配したデザイン。ヒップにかかる丈、リラックスフィットスタイル。', 'gender' => 'メンズ'],
            ['name' => "コットンブレンドオーバーシャツ",'price' => 73700,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのオーバーシャツ。エレクトリックパープルの色合いでツイルコットンブレンド素材を使用。フロントセンターにリングスナップ留め、背面にスナップボタンを備えた調節可能なタブ付き。サイドポケット、胸元と袖にパッチポケットを配したデザイン。ヒップにかかる丈、リラックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "パデッドジャケット",'price' => 92400,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのジャケット。ピグメントダイ仕上げを施したカーキベージュの平織りコットンを使用。胸元にFaceロゴのレザーパッチ付き。スタッドボタンアップ留め、キルティングを施したパッド入りライニングと取り外し可能な襟を配して仕上げたデザイン。ウエスト下の丈、レギュラーユニセックスフィットのスタイル。','gender' => 'メンズ'], 
            ['name' => "ナイロンフードデッドジャケット",'price' => 70400,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのジャケット。質感のあるブラックのナイロンを使用し、収納可能なフードを配したデザイン。フロントセンターにあしらった反射Faceロゴパッチがアクセントに。フロントジッパー&面ファスナー開閉スタイル、ウエストポケット付き。ヘムにドローコード入り。ヒップ丈、レギュラーユニセックスフィットのスタイル。','gender' => 'メンズ'], 
            ['name' => "ルーズフィットデニムジャケット",'price' => 68200,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックデニムジャケット。長めの袖と丈が特徴的なルーズフィットスタイル。環境にやさしい方法で栽培したリジッドデニムを使用。','gender' => 'メンズ'], 
            ['name' => "FACEロゴパッデッドジャケット",'price' => 92400,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのジャケット。ピグメントダイ仕上げを施したスモーキーパープルの平織りコットンを使用。バックにコントラストカラーのFaceロゴ、フロントにFaceロゴのレザーパッチ付き。スタッドボタンアップ留め、キルティングを施したパッド入りライニングと取り外し可能な襟を配して仕上げたデザイン。ウエスト下の丈、レギュラーユニセックスフィットのスタイル。','gender' => 'メンズ'], 
            ['name' => "サテンジャケット",'price' => 96800,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのジャケット。ドレープ感のあるブラックのサテンを使用。フロントジッパー開閉、胸ポケット、サイドシームとパッチポケットで仕上げたデザイン。ウエストと袖にドローコード入り、リラックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ロングボンバージャケット",'price' => 165000,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのベールジェードのボンバージャケット。バックに詩集。ウールを使用。コントラストカラーのリブ付きの袖口とヘムのディテール。レザープル付きのファスナー、控えめなポケットスナップ開閉、サイドシームポケットをあしらったデザイン。ミディ丈、リラックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "プリントレザージャケット",'price' => 360800,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのシングルブレストジャケット。ヴィンテージ風に仕上げたエクリュージュのディープグレインレザーを使用し、スタッズとコントラストカラーの糸のディテールをあしらったデザイン。背面にハンドペイント仕上げを施したシーズナルアートワークプリント入り。フロントセンターにボタン留め、パッチポケット付き。腰下丈のオーバーサイズフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ジッパージャケット",'price' => 81400,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのオーバーヘッドジャケット。ブラックの色合いで、コンシールのジッパー開閉を配して仕上げたデザイン。フロントポケット付き。レギュラーフィットスタイル、フロントにあしらったロゴパッチがポイント。','gender' => 'メンズ'], 
            

            ['name' => "グロウロゴセーター",'price' => 59400,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックセーター。フェイデッドブラックの子っとを使用。フロントセンターに配した暗闇で光るロゴがポイント。ネックラインとカフスはリブ編み仕上げ。リラックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "クルーネックスウェット",'price' => 46200,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックスウェット。ブラックのコットンブレンド素材を使用。カフスとヘムはリブ編み仕上げ。リラックスフィットのユニセックススタイル。','gender' => 'メンズ'], 
            ['name' => "クルーネックスウェット",'price' => 46200,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックスウェット。グレーのコットンブレンド素材を使用。カフスとヘムはリブ編み仕上げ。リラックスフィットのユニセックススタイル。','gender' => 'メンズ'], 
            ['name' => "ロゴフーディ",'price' => 61600,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのフーディセーター。フェイドフィニッシュを施したブラックの中厚コットンを使用。フロントセンターに配したUsen Studiosのスタンプロゴがポイント。フロントに大きめのポケット付き、リラックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ロゴフーディ",'price' => 61600,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのフーディセーター。フェイドフィニッシュを施したネオンピンクの中厚コットンを使用。フロントセンターに配したUsen Studiosのスタンプロゴがポイント。フロントに大きめのポケット付き、リラックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ジッパーセーター",'price' => 55000,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックのスウェットシャツ。中厚の起毛フリースコットンを使用。ファスナー付きタートルネックのディテール。サイドシームにUsen Studiosのピンクのラベル。レギュラーフィットのユニセックススタイル。','gender' => 'メンズ'], 
            ['name' => "ジッパーセーター",'price' => 55000,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのミネラルブルーのスウェットシャツ。中厚の起毛フリースコットンを使用。ファスナー付きタートルネックのディテール。サイドシームにUsen Studiosのピンクのラベル。レギュラーフィットのユニセックススタイル。','gender' => 'メンズ'], 
            ['name' => "クルーネックセーター",'price' => 36300,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのソフトグリーンのクルーネックセーター。中厚フリースコットンを使用。マイクロFaceロゴパッチ付き。レギュラーフィットのユニセックススタイル。','gender' => 'メンズ'], 
            ['name' => "クルーネックセーター",'price' => 36300,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのライトグレーメランジのクルーネックセーター。中厚フリースコットンを使用。マイクロFaceロゴパッチ付き。レギュラーフィットのユニセックススタイル。','gender' => 'メンズ'], 
            ['name' => "フードスウェットシャツ",'price' => 46200,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのフーディ。ブラックの色合いで、リブ編みバインディング仕上げのカンガルーポケットと胸元のFaceロゴパッチがポイント。中厚フリースコットンを使用。レギュラーフィットのユニセックススタイル。','gender' => 'メンズ'], 
            ['name' => "フードスウェットシャツ",'price' => 46200,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのフーディ。フェイデッドパープルの色合いで、リブ編みバインディング仕上げのカンガルーポケットと胸元のFaceロゴパッチがポイント。中厚フリースコットンを使用。レギュラーフィットのユニセックススタイル。','gender' => 'メンズ'], 
            ['name' => "フードスウェットシャツ",'price' => 46200,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのフーディ。ライトグレーメランジの色合いで、リブ編みバインディング仕上げのカンガルーポケットと胸元のFaceロゴパッチがポイント。中厚フリースコットンを使用。レギュラーフィットのユニセックススタイル。','gender' => 'メンズ'], 


            ['name' => "エンブロイダリーロゴセーター",'price' => 68200,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのダークブルークルーネックセーター。不均一にアシッドウォッシュ加工を施したコットンを使用。背面にあしらったUsen Studiosの刺繍がポイント。ネックライン、カフス、ヘムはリブ編み仕上げ。腰丈、レギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "エンブロイダリーロゴセーター",'price' => 55000,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックセーター。ライトグレー/ブラウンメランジのアルパカ＆ウールブレンド素材を使用。マルチメランジカラー仕上げ。胸元にUsen Studiosの刺繍入り、カフスとヘムはリブ編み仕上げ。ヒップにかかる丈のレギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ジャカードロゴセーター",'price' => 64900,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのセーター。エクリュ/ブラックの色合いで、全体にUsen Studiosのジャカードブランドロゴをループステッチで施したデザイン。コットンブレンド素材を使用、ネックライン、カフス、ヘムはリブ編み仕上げ。ヒップにかかる丈、リラックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ウールブレンドカーディガン",'price' => 64900,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのカーディガン。バブルピンク/スプリンググリーンの色合いで、全体にFaceロゴのタイルパターンをあしらったデザイン。ヘム側にマイクロFaceロゴパッチ付き。ウール＆コットンブレンド素材を使用。ネックライン、カフス、ヘムはリブ編み仕上げ。フロントセンターボタン留めスタイル。Vネック、レギュラーユニセックスフィットのスタイル。','gender' => 'メンズ'], 
            ['name' => "ウールブレンドカーディガン",'price' => 64900,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのカーディガン。タフィーブラウン/ブラックの色合いで、全体にFaceロゴのタイルパターンをあしらったデザイン。ヘム側にマイクロFaceロゴパッチ付き。ウール＆コットンブレンド素材を使用。ネックライン、カフス、ヘムはリブ編み仕上げ。フロントセンターボタン留めスタイル。Vネック、レギュラーユニセックスフィットのスタイル。','gender' => 'メンズ'], 
            ['name' => "テクスチャードセーター",'price' => 46200,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのセーター。ティールブルーのツートーンプリント糸を使用。質感のあるソフトな肌触りに仕上げたアイテム。ネックライン、カフス、ヘムはリブ編み仕上げ。胸元に配したマイクロFaceロゴパッチがアクセントに。レギュラーフィットのユニセックススタイル。','gender' => 'メンズ'], 
            ['name' => "クルーネックセーター ",'price' => 70400,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのカーディガンブラウンのクルーネックセーター。ウールモヘアブレンドを使用。ブラッシュド仕上げのヘアリーな表面。不均一な斑点模様の装飾。ネックライン、カフス、ヘムはリブ編み仕上げ。ヒップ丈、リラックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "クルーネックセーター",'price' => 55000,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックセーター。ミッドナイトブルーのコットンを使用。ネックライン、カフス、ヘムはリブ編み仕上げ。レギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ポロセーター ",'price' => 58300,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのニットポロセーター。フォレストグリーンのウールブレンド素材を使用。胸元にあしらったUsen Studiosのイニシャルと月の刺繍がポイント。ヒップ丈、フィット感のあるデザイン。','gender' => 'メンズ'], 
            ['name' => "FLORAGATANジャカードセーター",'price' => 64900,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックセーター。オフホワイト/マルチのコットン＆ウールブレンド素材を使用。今シーズンならではのUsen Studios Floragatanジャカードアートワークがポイント。アウトサイドシームとほつれた糸のディテールがアクセントに。レギュラー丈のフィット感のあるデザイン。','gender' => 'メンズ'], 
            ['name' => "ケーブルニットセーター",'price' => 81400,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックセーター。ミントグリーンの混紡糸を使用し、全体をケーブル編みで仕上げたデザイン。ヒップ下丈のリラックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ウール＆カシミア Vネックセーター",'price' => 75900,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのセーター。アンスラサイトグレーの色合いで、Vネックラインとピンクフラッグラベルのディテールがポイント。レスポンシブル・ウール・スタンダード（RWS）認証のウール＆カシミヤブレンド素材を使用。ネックライン、カフス、ヘムにあしらったリブディテールがアクセントに。レギュラーシルエットスタイル。','gender' => 'メンズ'], 


            ['name' => "グロウプリントTシャツ ",'price' => 36300,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのTシャツ。ガーメントダイ仕上げを施したフェイデッドブラックのコットンを使用。暗闇で光るシーズナルブランドロゴとリブ編みクルーネックラインが特徴。レギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "コットンTシャツ ",'price' => 23650,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのTシャツ。オプティックホワイトの薄手ジャージーコットンを使用。リブ編みネックラインと背面にあしらったUsen Studiosのロゴパッチがポイント。レギュラーフィットのユニセックススタイル。','gender' => 'メンズ'], 
            ['name' => "ロゴTシャツ",'price' => 34100,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのTシャツ。ブラックの中厚ジャージーコットンを使用。フロントセンターにUsen Studiosロゴのディテール。リラックスフィットのスタイル。','gender' => 'メンズ'], 
            ['name' => "ロゴTシャツ",'price' => 34100,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのTシャツ。マッシュルームベージュの中厚ジャージーコットンを使用。フロントセンターにUsen Studiosロゴのディテール。リラックスフィットのスタイル。','gender' => 'メンズ'], 
            ['name' => "ロゴ ロングスリーブTシャツ",'price' => 38500,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのロングスリーブTシャツ。ブラックの中厚ジャージーコットンを使用。フロントセンターにUsen Studiosロゴのディテール。レギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ロゴ ロングスリーブTシャツ",'price' => 38500,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのロングスリーブTシャツ。オプティックホワイトの中厚ジャージーコットンを使用。フロントセンターにUsen Studiosロゴのディテール。レギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ロゴTシャツ",'price' => 33000,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのペールグレーメランジのTシャツ。スプレー仕上げを施したコットン＆ヘンプブレンド素材を使用。フロントにUsen Studios 1996のロゴスタンプ付き。ネックライン、カフス、ヘムにダメージ加工。リラックスユニセックスフィットのスタイル。','gender' => 'メンズ'], 
            ['name' => "スクリブルTシャツ",'price' => 34100,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのフェイデッドブラックのTシャツ。薄手のジャージーコットンを使用し、フロントにFaceロゴをあしらったデザイン。落書きスタイルのアニメーションプリント入り。リブ編みクルーネック、リラックスユニセックスフィットのスタイル。','gender' => 'メンズ'], 
            ['name' => "スクリブルTシャツ",'price' => 34100,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのオプティックホワイトのTシャツ。薄手のジャージーコットンを使用し、フロントにFaceロゴをあしらったデザイン。落書きスタイルのアニメーションプリント入り。リブ編みクルーネック、リラックスユニセックスフィットのスタイル。','gender' => 'メンズ'], 
            ['name' => "クルーネックTシャツ",'price' => 22000,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのクルーネックTシャツ。ブラックの薄手ジャージーを使用。胸元にFaceロゴパッチ付き。レギュラーフィットのユニセックススタイル。','gender' => 'メンズ'], 
            ['name' => "クルーネックTシャツ",'price' => 24750,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのオプティックホワイトTシャツ。薄手ジャージーコットンを使用。胸元にパッチポケット付き。レギュラーフィットのユニセックススタイル。','gender' => 'メンズ'], 
            ['name' => "スクリブル ロングスリーブTシャツ",'price' => 29700,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのロングスリーブTシャツ。ホワイトマルチカラーの色合いで、全体に落書きスタイルのプリントを施したデザイン。カフスにあしらったマイクロFaceロゴパッチがアクセントに。薄手メッシュ素材を使用、カフスとヘムはローエッジ仕上げ。レギュラー丈、フィット感のあるユニセックスフィットスタイル。','gender' => 'メンズ'], 


            ['name' => "ルーズフィットジーンズ - 2021",'price' => 65450,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのルーズフィットジーンズ。ミッドブルーの色合いで、ミッドウエスト、長めの丈に仕立てたワイドレッグスタイル。ファイブポケットデザイン。シーズナルガーメントダイ仕上げを施したコットンのリジッドデニムを使用。ダメージ感のあるディテールがポイント。','gender' => 'メンズ'], 
            ['name' => "レギュラーフィットジーンズ - 1996",'price' => 50050,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのレギュラーフィットジーンズ。ブラックの色合いで、ミッドウエスト、レギュラー丈のストレートレッグスタイル。ファイブポケットデザイン。1996ジーンズには、コットンのリジッドデニムを使用。','gender' => 'メンズ'], 
            ['name' => "レギュラーフィットジーンズ - 1996",'price' => 50050,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのダークブルーのジーンズ。ミッドウエスト、レギュラー丈のストレートレッグスタイル、レギュラーフィットのスタイル。ファイブポケットデザイン。1996ジーンズには、コットンのリジッドデニムを使用。','gender' => 'メンズ'], 
            ['name' => "ルーズブーツカットジーンズ",'price' => 53900,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックジーンズ。ルーズブーツカットに仕立てた、ミッドライズウエストのレギュラー丈スタイル。ファイブポケットデザイン。環境にやさしい方法で栽培したリジッドデニムを使用。','gender' => 'メンズ'], 
            ['name' => "ルーズブーツカットジーンズ",'price' => 59400,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのミッドブルージーンズ。ルーズブーツカットに仕立てた、ミッドライズウエストのロング丈スタイル。ファイブポケットデザイン。環境にやさしい方法で栽培したリジッドデニムを使用。','gender' => 'メンズ'], 
            ['name' => "フレアフィット ジーンズ",'price' => 41250,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックジーンズ。ミッドライズウエストのレギュラー丈フレアフィットスタイル。ファイブポケットデザイン。環境にやさしい方法で栽培したリジッドデニムを使用。','gender' => 'メンズ'], 
            ['name' => "フレアフィット コーデュロイジーンズ",'price' => 45650,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのベージュコーデュロイジーンズ。ミッドライズウエストのレギュラー丈に仕立てたフレアフィットスタイル。ファイブポケットデザイン。','gender' => 'メンズ'], 
            ['name' => "リラックスフィットジーンズ - 2003",'price' => 53900,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのリラックスフィットジーンズ。ダークグレー/グレーの色合いで、ローウエスト、レギュラー丈のストレートレッグスタイル。ファイブポケットデザイン。2003ジーンズには、コットンのリジッドデニムを使用。','gender' => 'メンズ'], 
            ['name' => "リラックスフィットジーンズ - 2003",'price' => 58850,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのリラックスフィットジーンズ。ペールイエロー/ペールブルーの色合いで、ローウエスト、レギュラー丈のストレートレッグスタイル。ファイブポケットデザイン。2003ジーンズには、コットンのリジッドデニムを使用。','gender' => 'メンズ'], 
            ['name' => "ルーズフィットジーンズ - 1989",'price' => 63800,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのルーズフィットジーンズ。ライラック/ブルーの色合いで、ローウエスト、レギュラー丈のストレートレッグスタイル。ファイブポケットデザイン。インディゴの染色を施したコットンツイルのノンストレッチデニムを使用。','gender' => 'メンズ'], 
            ['name' => "ルーズフィットジーンズ",'price' => 60500,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのルーズフィットジーンズ。ブラックのリジッドデニムを使用。ワイドなストレートカットシルエットのレギュラー丈スタイル。環境にやさしい方法で栽培したコットンを使用、スリムベルトでハイライズからミッドライズまで調節可能なデザイン。','gender' => 'メンズ'], 
            ['name' => "ルーズフィットジーンズ",'price' => 53900,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのジーンズ。ヴィンテージブラックのリジッドデニムを使用。ディープライズ、ルーズレッグスタイル。','gender' => 'メンズ'], 


            ['name' => "テーラードプリーツショートパンツ",'price' => 42900,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックのプリーツショートパンツ。ウールブレンド素材を使用。レギュラーフィットスタイル。フロントにアングルポケットと、バックにボタン開閉式ジェッテッドポケットの仕上げ。','gender' => 'メンズ'], 
            ['name' => "コットンスウェットショートパンツ",'price' => 34100,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのスウェットショートパンツ。ブラックの中厚コットンジャージーを使用。伸縮性のあるウエストバンドとロゴプリント入りパッチポケットがポイント。リラックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "コットンスウェットショートパンツ",'price' => 34100,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのスウェットショートパンツ。スチールグレーのオーガニックコットンを使用。伸縮性のあるウエストバンド付き。リラックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ルーズフィット デニムショートパンツ",'price' => 52800,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのショートパンツ。ミッドブルーのコットンのリジッドデニムを使用。ダメージ感のあるディテールがポイント。ライズを調節可能なベルト付き、膝丈のルーズフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "レギュラーフィット ショートパンツ",'price' => 34100,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックのショートパンツ。コットンブレンドを使用。ピンクのUsen Studiosラベルのディテール。ベルトループとサイドシームポケット、バックポケットをあしらって仕上げたデザイン。バックに伸縮性のあるウエストバンドを配した、ミディ丈のレギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "レギュラーフィット ショートパンツ",'price' => 34100,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのヘーゼルベージュのショートパンツ。コットンブレンドを使用。ピンクのUsen Studiosのラベルのディテール。ベルトループとサイドシームポケット、バックポケットをあしらって仕上げたデザイン。バックに伸縮性のあるウエストバンドを配した、ミディ丈のレギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "コットン スウェットショートパンツ",'price' => 29700,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのスウェットショートパンツ。ブラックの中厚コットンを使用。左サイドポケットの下にFaceロゴパッチをあしらったデザイン。サイドポケットとパッチポケット付き。伸縮性のあるウエストバンドを配した、ミッド丈、レギュラーユニセックスフィットのスタイル。','gender' => 'メンズ'], 
            ['name' => "コットン スウェットショートパンツ",'price' => 29700,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのスウェットショートパンツ。ライトグレーメランジの中厚コットンを使用。左サイドポケットの下にFaceロゴパッチをあしらったデザイン。サイドポケットとパッチポケット付き。伸縮性のあるウエストバンドを配した、ミッド丈、レギュラーユニセックスフィットのスタイル。','gender' => 'メンズ'], 
            ['name' => "コットン スウェットショートパンツ",'price' => 29700,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのスウェットショートパンツ。ソフトグリーンの色合い。中厚コットンを使用。左サイドポケットの下にFaceロゴパッチをあしらったデザイン。サイドポケットとパッチポケット付き。伸縮性のあるウエストバンドを配した、ミッド丈、レギュラーユニセックスフィットのスタイル','gender' => 'メンズ'], 
            ['name' => "スイムショーツ",'price' => 37400,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのスイムショーツ。シェルベージュの色合いで、脚部分に配したUsen Studiosロゴの反射テープがポイント。サイドシームポケット付き。伸縮性のあるウエストバンドと機能的なドローストリングを配したデザイン。レギュラーライズのリラックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ルーズフィット デニムショートパンツ",'price' => 57200,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのデニムショートパンツ。ライトピンク/グレーの色合いで、コットンのリジッドインディゴデニムを使用。ファイブポケットデザイン。膝下丈、ゆったりとしたユニセックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ルーズフィット デニムショートパンツ",'price' => 48400,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのショートパンツ。ペールイエロー/ペールブルーの色合いで、ミッドライズウエスト、膝丈のルーズフィットスタイル。スリムベルト付き。コットンのリジッドデニムを使用。','gender' => 'メンズ'], 


            ['name' => "テーラードトラウザーズ",'price' => 55550,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのテーラードスーツトラウザーズ。ブラックのウールブレンド素材を使用。脚部の前後にセンタープレス入り。アングルサイドシームポケットとバックに2つのジェッテッドポケット付き。丈が長めのレギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "リラックスフィットトラウザーズ ",'price' => 55000,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックトラウザーズ。ウールブレンド素材を使用。伸縮性のあるウエストバンドとドローストリングを配したデザイン。サイドポケットとバックパッチポケット付き。長めの丈、リラックスフィット、レギュラーライズウエストのスタイル。','gender' => 'メンズ'], 
            ['name' => "ツイルトラウザーズ",'price' => 46200,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックトラウザーズ。ツイル織コットンを使用。サイドポケットとバックウェルトポケット付き。レギュラー丈レギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ツイルトラウザーズ ",'price' => 46200,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのトラウザーズ。グラファイトグレーのツイル織コットンを使用。サイドポケットとバックウェルトポケット付き。レギュラー丈レギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "プリントデニムトラウザーズ",'price' => 70400,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのトラウザーズ。ミッドブルーのコットンデニムを使用。全体にボタンプリント入り。ブラスのスタッドボタンとオーバル形のパッチポケットを配したデザイン。フレアレッグ、ロング丈のレギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "ウールトラウザーズ",'price' => 55000,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックのスーツトラウザーズ。やわらかくドレープ感のあるウールを使用。伸縮性のあるウエストバンド、サイドポケット、背面にパッチポケットのディテール。長めの丈、リラックスフィット、レギュラーライズウエストのスタイル。','gender' => 'メンズ'], 
            ['name' => "コンバーチブル トラウザーズ",'price' => 70400,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのウォッシュド アントライスのトラウザーズ。ストーンウォッシュ加工を施したリップストップコットンを使用。Usen Studiosロゴの刺繍。機能的ファスナーで短い丈に調節可能。アングルポケットとカーゴポケットをあしらったデザイン。レギュラーライズウエスト、ワイドレッグ、アジャスタブル丈に仕立てた、リラックスフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "テーラードトラウザーズ",'price' => 58300,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックテーラードスーツトラウザーズ。ウールブレンド素材を使用。サイドポケットとバックウェルトポケットを配したデザイン。ヘムにトップステッチ入り、レギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "テーラードトラウザーズ",'price' => 58300,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのマッドグレーのテーラードスーツトラウザーズ。ウールブレンド素材を使用。サイドポケットとバックウェルトポケットを配したデザイン。ヘムにトップステッチ入り、レギュラーフィットスタイル。','gender' => 'メンズ'], 
            ['name' => "プリントトラウザーズ",'price' => 64900,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのトラウザーズ。ブルー/ベージュの色合いで、全体にサブリミナルプリントを施したデザイン。ジャカード仕上げ、伸縮性のあるウエストバンドとドローコード付き。Usen Studiosの刺繍入り、脚部の両側にトーナルカラーのスナップボタン付き。','gender' => 'メンズ'], 
            ['name' => "レギュラーフィット トラウザーズ",'price' => 55000,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのトラウザーズ。ピグメントダイ仕上げを施したカーキベージュの平織厚手コットンを使用。バックウエストバンドにFaceロゴのレザーパッチ付き。フロントにアングルポケットとコインポケット、バックにパッチポケット付き。ローライズウエスト、長めの丈に仕上げたレギュラーユニセックスフィットのスタイル。','gender' => 'メンズ'], 
            ['name' => "レギュラーフィット トラウザーズ",'price' => 46200,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのトラウザーズ。質感のあるブラックのナイロンを使用。反射Faceロゴパッチがアクセントに。伸縮性のあるウエストバンド、サイドシームポケットとバックパッチポケット付き。ミッドライズウエスト、長めの丈に仕上げたレギュラーユニセックスフィットのスタイル。','gender' => 'メンズ'], 


            ['name' => "レザーボンバージャケット",'price' => 266200,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのレザージャケット。ピグメント加工を施したブラックのレザーを使用。コントラストカラーの襟、カフス、ヘムはリブ編み仕上げ。フロントセンタージッパー開閉スタイル、ウェルトポケットと2つのジッパー付きジェッテッドポケット付き。ウエスト丈、リラックスフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ダブルブレストトレンチコート",'price' => 188100,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのベルト付きダブルブレスト トレンチコート。全体にプリントを施したダークブラウンのコットンを使用。ボタン留めスタイル、ウェルトポケット付き。ミディ丈レギュラーフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ダブルブレスト トレンチジャケット",'price' => 96800,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのダブルブレスト トレンチジャケット。ミリタリーグリーンのコットンツイルを使用。ボタン留め、裾部分にベルト付き。ウエスト丈、リラックスフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ダブルブレスト トレンチジャケット",'price' => 96800,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのダブルブレスト トレンチジャケット。コールドベージュのコットンツイルを使用。ボタン留め、裾部分にベルト付き。ウエスト丈、リラックスフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "リラックスフィットジャケット",'price' => 101200,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのジャケット。ベージュのコットン＆ウールブレンド素材を使用。デニムジャケット仕立て、フロントのレースディテールがポイント。ウエスト下の丈、リラックスフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ルーズフィット デニムジャケット",'price' => 72600,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのライトブルーデニムジャケット。長めの袖と丈を配したルーズフィットスタイル。コットンのリジッドデニムを使用。','gender' => 'ウィメンズ'], 
            ['name' => "デニム ダブルブレストトレンチコート",'price' => 188100,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのダブルブレストトレンチコート。縦糸をピュアインディゴで染色した、ライトブルーのコットンデニムを使用。カフスにUsen Studiosのシーズナルロゴラベル付き。フロントボタンとベルトで開閉、カフスにメタルバックル付きベルトを配したデザイン。デコラティブなフラップディテールをあしらったウェルトポケット付き。丈が長めのリラックスフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "デニムジャケット - レギュラーフィット",'price' => 92400,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのデニムジャケット。ライトブルーのコットンのリジッドデニムを使用。胸ポケットがアクセントに。両サイドに柔軟なボーンを配してアワーグラスシルエットに仕立てた、レギュラー丈のレギュラーフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "パデッドジャケット",'price' => 92400,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのジャケット。ピグメントダイ仕上げを施したカーキベージュの平織コットンを使用。胸元にFaceロゴのレザーパッチ付き。スタッドボタンアップ留め、キルティングを施したパッド入りライニングと取り外し可能な襟を配して仕上げたデザイン。ウエスト下の丈、レギュラーユニセックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "FACEロゴ パッデッドジャケット",'price' => 92400,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのジャケット。ピグメントダイ仕上げを施したスモーキーパープルの平織コットンを使用。バックにコントラストカラーのFaceロゴ、フロントにFaceロゴのレザーパッチ付き。スタッドボタンアップ留め、キルティングを施したパッド入りライニングと取り外し可能な襟を配して仕上げたデザイン。ウエスト下の丈、レギュラーユニセックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ダブルブレストジャケット",'price' => 107800,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックのダブルブレストスーツジャケット。ウールブレンドを使用。コントラストのあるサテンラペルが特徴。ウェルト胸ポケットで仕上げ。ウエスト丈でリラックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ダブルブレストジャケット",'price' => 107800,'category_id' => 1,'release_date' => new DateTime(),'detail' => 'Usen Studiosのオーバージーンパープルのダブルブレストスーツジャケット。ウールブレンドを使用。コントラストのあるサテンラペルが特徴。ウェルト胸ポケットで仕上げ。ウエスト丈でリラックスフィットのスタイル。','gender' => 'ウィメンズ'], 


            ['name' => "クルーネックセーター",'price' => 46200,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックセーター。ブラックのコットンブレンド素材を使用。カフスとヘムはリブ編み仕上げ。リラックスフィットのユニセックススタイル。','gender' => 'ウィメンズ'], 
            ['name' => "スタンプロゴスウェットシャツ",'price' => 49500,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックスウェットシャツ。ブラックの色合いで、フロントのロゴプリントがポイント。リラックスフィットスタイル。リブ編みネック、カフス、ヘムを配したデザイン。ピグメントダイ仕上げを施したコットン製の厚手フリースを使用。','gender' => 'ウィメンズ'], 
            ['name' => "スタンプロゴスウェットシャツ",'price' => 49500,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのオプティックホワイト スウェットシャツ。リブ編みクルーネック、カフス、ヘムがポイント。リラックスフィットスタイル。コットンを使用。フロントにコントラストを効かせたUsen Studiosのスタンプロゴのディテール付き。','gender' => 'ウィメンズ'], 
            ['name' => "プリントセーター",'price' => 58300,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックスウェットシャツ。フェイドフィニッシュを施したダスティパープルのコットンブレンド素材を使用。フロントにUsen Studiosのシーズナルスクリーンプリント入り。リラックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "グラフィックフーディセーター",'price' => 64900,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのフーディ。フェイドフィニッシュを施したフェイデッドブラックのコットンを使用。フロントにカットアウトを施したシーズナルグラフィック入り。リラックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ジッパーフーディ",'price' => 58300,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのフーディ。ダスティベージュの色合いで、胸元のマイクロFaceロゴパッチとフードの縁に施したFaceロゴ刺繍がポイント。ジッパー開閉、コンシールサイドシームポケット付き。中厚起毛フリースを使用。リラックスユニセックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ジッパーフーディ",'price' => 58300,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのフーディ。シーグリーンの色合いで、胸元のマイクロFaceロゴパッチとフードの縁に施したFaceロゴ刺繍がポイント。ジッパー開閉、コンシールサイドシームポケット付き。中厚起毛フリースを使用。リラックスユニセックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "フーデッドセーター",'price' => 55000,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのミネラルブルーのフーディセーター。中厚の起毛フリースコットンを使用。サイドシームにUsen Studiosのラベル。レギュラー丈、リラックスユニセックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "フーデッドセーター",'price' => 55000,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのローズウッドレッドのフーディセーター。中厚の起毛フリースコットンを使用。サイドシームにUsen Studiosのラベル。レギュラー丈、リラックスユニセックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "プリントフーディ",'price' => 59400,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのスウェットシャツ。オレンジ/イエローの色合いで、ドローストリング入りフードを配したデザイン。フロントに施したプリントがポイント。中厚フリースに仕上げたコットンのヒートリアクティブ素材を使用。クロップド丈、フィット感のあるユニセックスシルエット。','gender' => 'ウィメンズ'], 
            ['name' => "プリントフーディ",'price' => 59400,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのスウェットシャツ。グレー/パープルの色合いで、ドローストリング入りフードを配したデザイン。フロントに施したプリントがポイント。中厚フリースに仕上げたコットンのヒートリアクティブ素材を使用。クロップド丈、フィット感のあるユニセックスシルエット。','gender' => 'ウィメンズ'], 
            ['name' => "クルーネックセーター",'price' => 46200,'category_id' => 2,'release_date' => new DateTime(),'detail' => 'Usen Studiosのライトキャメルのクルーネックスウェットシャツ。中厚の起毛コットンを使用。サイドシームにUsen Studiosのピンクロゴ。レギュラー丈、リラックスユニセックスフィットのスタイル。','gender' => 'ウィメンズ'], 


            ['name' => "ワイドリブカーディガン ",'price' => 55000,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのカーディガン。コールドベージュのリネンブレンド素材を使用した、ワイドリブ編みデザイン。やや透け感のある不均一な風合いがポイント。ウエスト丈に仕上げたフィット感のあるフロントセンターボタン留めスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "モヘアブレンドセーター",'price' => 51700,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのセーター。ソフトな肌触りに仕上げたシャーベットピンクのモヘア＆ウールブレンド素材を使用。透け感のあるオープンニット仕上げ。Vネックラインにチェーンリンク付き、レギュラーフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ワイドリブセーター",'price' => 58300,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのセーター。ダークブラウンの色合い。リネンブレンド素材を使用した、ワイドリブ編みデザイン。やや透け感のある不均一な風合いがポイント。ネックラインにボタン留めのスリット入り、フロントセンターにスリットディテール。シャツカラー、長めの袖を配した、腰丈のフィット感のあるデザイン。','gender' => 'ウィメンズ'], 
            ['name' => "クルーネックウールカーディガン",'price' => 49500,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックカーディガン。ブラックの薄手ウールを使用。トーナルカラーのFaceロゴパッチ付き。リブ編みの襟と袖口、裾ディテールがポイント。ややクロップド丈、レギュラーフィットのユニセックススタイル。','gender' => 'ウィメンズ'], 
            ['name' => "クルーネックウールカーディガン",'price' => 49500,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックカーディガン。スカイブルーメランジの色合い。薄手ウールを使用。トーナルカラーのFaceロゴパッチ付き。リブ編みの襟と袖口、裾ディテールがポイント。ややクロップド丈、レギュラーフィットのユニセックススタイル。','gender' => 'ウィメンズ'], 
            ['name' => "クルーネックウールカーディガン",'price' => 49500,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックカーディガン。バブルピンクの色合い。薄手ウールを使用。トーナルカラーのFaceロゴパッチ付き。リブ編みの襟と袖口、裾ディテールがポイント。ややクロップド丈、レギュラーフィットのユニセックススタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ウールニットカーディガン",'price' => 55000,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックニットカーディガン。トーナルカラーのフェイスロゴパッチとVネックスタイル、リブ編みの襟、袖口、裾がポイント。レスポンシブル・ウール・スタンダード（RWS）認証のウールを使用。','gender' => 'ウィメンズ'], 
            ['name' => "ウールニットカーディガン",'price' => 55000,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのニットカーディガン。インディゴメランジの色合いで、トーナルカラーのFaceロゴパッチとVネックスタイル、リブ編みのカラー、カフス、ヘムがポイント。','gender' => 'ウィメンズ'], 
            ['name' => "ウールニットカーディガン",'price' => 55000,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのカーディガン。ボトルグリーンの色合い。薄手ウールを使用。小さなFaceロゴパッチがアクセントに。リブ編みVネックライン、カフス、ヘムを配した、リラックスユニセックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ウールニットカーディガン",'price' => 55000,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのグレーメランジニットカーディガン。トーナルカラーのフェイスロゴパッチとVネックスタイル、リブ編みの襟、袖口、裾がポイント。レスポンシブル・ウール・スタンダード（RWS）認証のウールを使用。','gender' => 'ウィメンズ'], 
            ['name' => "クルーネックセーター",'price' => 38500,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックセーター。ティールブルーの色合い。プリント入りツートーンリサイクル糸を使用。質感のある仕上げがポイント。ネックライン、カフス、ヘムはリブ編み仕上げ。マイクロFaceロゴパッチがアクセントに。クロップド丈、フィット感のあるユニセックスフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "クルーネックセーター",'price' => 38500,'category_id' => 3,'release_date' => new DateTime(),'detail' => 'Usen Studiosのクルーネックセーター。バブルガムピンクメランジのプリント入りツートーンリサイクル糸を使用。質感のある仕上げがポイント。ネックライン、カフス、ヘムはリブ編み仕上げ。マイクロFaceロゴパッチがアクセントに。クロップド丈、フィット感のあるユニセックスフィットスタイル。','gender' => 'ウィメンズ'], 


            ['name' => "ロゴロングスリーブTシャツ ",'price' => 38500,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのロングスリーブTシャツ。オプティックホワイトの中厚ジャージーコットンを使用。フロントセンターにUsen Studiosロゴのディテール、リラックスフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ロゴTシャツ",'price' => 34100,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのブラックのクルーネックTシャツ。フロントセンターにブランドロゴをあしらい、レギュラーフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ロゴTシャツ",'price' => 34100,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのクルーネックTシャツ。フルオグリーンの色合いで、フロントセンターにブランドロゴをあしらったデザイン。レギュラーフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ロゴTシャツ",'price' => 34100,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのパステルグリーンTシャツ。環境にやさしい方法で栽培したコットンを使用。フロントにあしらったUsen Studiosのスタンプロゴがアクセントに。','gender' => 'ウィメンズ'], 
            ['name' => "ロゴTシャツ",'price' => 34100,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのクルーネックTシャツ。シャンパンベージュの色合いで、フロントセンターにブランドロゴをあしらったデザイン。レギュラーフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "コットンTシャツ",'price' => 23650,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのTシャツ。オプティックホワイトの薄手ジャージーコットンを使用。リブ編みネックラインと背面にあしらったUsen Studiosのロゴパッチがポイント。レギュラーフィットのユニセックススタイル。','gender' => 'ウィメンズ'], 
            ['name' => "スリーブレスTシャツ",'price' => 22000,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのブラックスリーブレスTシャツ。薄手のジャージーコットンを使用。リブ編みネックラインのディテール。背面にUsen Studiosのピンクのラベル。レギュラーフィットのユニセックススタイル。','gender' => 'ウィメンズ'], 
            ['name' => "スリーブレスTシャツ",'price' => 22000,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのムドグレイのスリーブレスTシャツ。薄手のジャージーを使用。リブ編みリブ編みネックラインと背面にUsen Studiosのピンクラベルのディテール。レギュラーフィットのユニセックススタイル。','gender' => 'ウィメンズ'], 
            ['name' => "スリーブレスTシャツ",'price' => 22000,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのローズウッドレッドのスリーブレスTシャツ。薄手のジャージーを使用。リブ編みリブ編みネックラインと背面にUsen Studiosのピンクラベルのディテール。レギュラーフィットのユニセックススタイル。','gender' => 'ウィメンズ'], 
            ['name' => "スリーブレスTシャツ",'price' => 22000,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのオプティックホワイトのスリーブレスTシャツ。薄手のジャージーを使用。リブ編みリブ編みネックラインと背面にUsen Studiosのピンクラベルのディテール。レギュラーフィットのユニセックススタイル。','gender' => 'ウィメンズ'], 
            ['name' => "プリントTシャツ",'price' => 37400,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのTシャツ。フェイデッドブラックの薄手ジャージーコットンを使用。シーズナルアニメーションプリントがポイント。リブ編みクルーネック、リラックスユニセックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "プリントTシャツ",'price' => 37400,'category_id' => 4,'release_date' => new DateTime(),'detail' => 'Usen StudiosのTシャツ。ポーセリンホワイトの薄手ジャージーコットンを使用。シーズナルアニメーションプリントがポイント。リブ編みクルーネック、リラックスユニセックスフィットのスタイル。','gender' => 'ウィメンズ'], 



            ['name' => "リラックスフィットジーンズ - 2022",'price' => 53900,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのリラックスフィットジーンズ。ブラックの色合いで、ハイウエスト、長めの丈に仕立てたワイドレッグスタイル。ファイブポケットデザイン。2022ジーンズには、コットンのリジッドデニムを使用。','gender' => 'ウィメンズ'], 
            ['name' => "リラックスフィットジーンズ - 2022",'price' => 56650,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのリラックスフィットジーンズ。ベージュの色合いで、ハイライズウエスト、フルレングスに仕立てたワイドレッグスタイル。ファイブポケットデザイン。2022ジーンズには、コットンのリジッドデニムを使用。','gender' => 'ウィメンズ'], 
            ['name' => "レギュラーフィットジーンズ - 1977",'price' => 52250,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのレギュラーフィットジーンズ。ブラックの色合いで、ハイウエスト、レギュラー丈のブーツカットレッグスタイル。ファイブポケットデザイン。1977ジーンズには、コットンのリジッドデニムを使用。','gender' => 'ウィメンズ'], 
            ['name' => "レギュラーフィットジーンズ - 1977",'price' => 50050,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのレギュラーフィットジーンズ。インディゴブルーの色合いで、ハイウエスト、レギュラー丈のブーツカットレッグスタイル。ファイブポケットデザイン。1977ジーンズには、コットンのリジッドデニムを使用。','gender' => 'ウィメンズ'], 
            ['name' => "レギュラーフィットジーンズ - 1977",'price' => 55000,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのレギュラーフィットジーンズ。ミッドブルーの色合いで、ハイウエスト、レギュラー丈のブーツカットレッグスタイル。ファイブポケットデザイン。1977ジーンズには、コットンのリジッドデニムを使用。','gender' => 'ウィメンズ'], 
            ['name' => "レギュラーフィットジーンズ - MECE",'price' => 50050,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのレギュラーフィットジーンズ。ブラックの色合いで、ハイウエスト、クロップド丈のストレートレッグスタイル。ファイブポケットデザイン。Meceジーンズには、コットンのリジッドデニムを使用。','gender' => 'ウィメンズ'], 
            ['name' => "レギュラーフィットジーンズ - MECE ASH",'price' => 56650,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのレギュラーフィットジーンズ。ブラックの色合いで、ハイウエスト、クロップド丈のストレートレッグスタイル。ファイブポケットデザイン。Meceジーンズには、コットンのリジッドデニムを使用。','gender' => 'ウィメンズ'], 
            ['name' => "レギュラーフィットジーンズ - MECE",'price' => 52250,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのレギュラーフィットジーンズ。エクリュ/エクリュの色合いで、ハイウエスト、クロップド丈のストレートレッグスタイル。ファイブポケットデザイン。コットンの横糸を用いたデニムを使用。','gender' => 'ウィメンズ'], 
            ['name' => "リラックスフィットジーンズ - 2022",'price' => 58850,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのリラックスフィットジーンズ。ライトブルーの色合いで、ハイウエスト、長めの丈に仕立てたワイドレッグスタイル。ファイブポケットデザイン。2022ジーンズには、コットンのリジッドデニムを使用。','gender' => 'ウィメンズ'], 
            ['name' => "リラックスフィットジーンズ - 2022",'price' => 56650,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのリラックスフィットジーンズ。ミッドブルーの色合いで、ハイウエスト、長めの丈に仕立てたワイドレッグスタイル。ファイブポケットデザイン。2022ジーンズには、コットンのリジッドデニムを使用。','gender' => 'ウィメンズ'], 
            ['name' => "リラックスフィットジーンズ - 2022",'price' => 67100,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのリラックスフィットジーンズ。ブラックの色合いで、ハイウエスト、長めの丈に仕立てたワイドレッグスタイル。ファイブポケットデザイン。2022ジーンズには、コットンのリジッドデニムを使用。','gender' => 'ウィメンズ'], 
            ['name' => "ルーズフィットジーンズ - 2021",'price' => 65400,'category_id' => 5,'release_date' => new DateTime(),'detail' => 'Usen Studiosのルーズフィットジーンズ。ミッドブルーの色合いで、ミッドウエスト、長めの丈に仕立てたワイドレッグスタイル。ファイブポケットデザイン。2021ジーンズには、シーズナルガーメントダイ仕上げを施したコットンを使用。ダメージ感のあるディテールがポイント。','gender' => 'ウィメンズ'], 


            ['name' => "ルーズフィットデニムショートパンツ ",'price' => 57200,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのデニムショートパンツ。ライトピンク/グレーの色合いで、コットンのリジッドインディゴデニムを使用。ファイブポケットデザイン。膝下丈、ゆったりとしたユニセックスフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "チェックフランネルショートパンツ",'price' => 34100,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのショートパンツ。グレー/ダークグリーンのチェックパターンをあしらったツイル織フランネルコットンを使用。フロントポケットに施したマイクロFaceロゴパッチ刺繍がポイント。伸縮性のあるウエストバンド、サイドシームポケットとバックパッチポケット付き。ミッドライズウエスト、太腿半ば丈に仕上げたレギュラーユニセックスフィットのスタイル','gender' => 'ウィメンズ'], 
            ['name' => "ダメージショートパンツ",'price' => 58300,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのショートパンツ。ベージュのコットンを使用。ダメージ感のあるホールディテール、切りっぱなしのヘムとフロントからバックまで伸びるジッパー開閉が特徴。ミッドライズウエストのフィット感のあるシルエット。','gender' => 'ウィメンズ'], 
            ['name' => "キャンバスコットン ショートパンツ",'price' => 44000,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのショートパンツ。ピグメントダイ仕上げを施したスモーキーパープルの厚手キャンバスコットンを使用。バックにテープディテールをあしらったデザイン。バックウエストバンドに配したFaceロゴパッチがアクセントに。フロントにコインポケット付きアングルポケット、バックにパッチポケット付き。ミッドライズウエスト、膝丈に仕上げたレギュラーユニセックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "コットン スウェットショートパンツ",'price' => 29700,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのスウェットショートパンツ。ライトグレーメランジの中厚コットンを使用。左サイドポケットの下にFaceロゴパッチをあしらったデザイン。サイドポケットとパッチポケット付き。伸縮性のあるウエストバンドを配した、ミッド丈、レギュラーユニセックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "コットン スウェットショートパンツ",'price' => 29700,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのスウェットショートパンツ。ブラックの中厚コットンを使用。左サイドポケットの下にFaceロゴパッチをあしらったデザイン。サイドポケットとパッチポケット付き。伸縮性のあるウエストバンドを配した、ミッド丈、レギュラーユニセックスフィットのスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "サテンショートパンツ",'price' => 58300,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのショートパンツ。ブラックのサテン素材を使用、ロールアップヘムがポイント。後ろは伸縮性のあるデザイン、フロントポケットとバックポケット付き。ショート丈レギュラーフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "サテンショートパンツ",'price' => 58300,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのショートパンツ。アプリコットオレンジのサテン素材を使用、ロールアップヘムがポイント。後ろは伸縮性のあるデザイン、フロントポケットとバックポケット付き。ショート丈レギュラーフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ダメージ デニムショートパンツ",'price' => 51700,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのショートパンツ。ブラックの色合いで、ハイライズのフィット感のあるシルエットに仕上げたデザイン。裾はローエッジ仕上げ、ダメージ感のあるホールディテールがポイント。コットンのリジッドデニムを使用。','gender' => 'ウィメンズ'], 
            ['name' => "ダメージ デニムショートパンツ",'price' => 47300,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのデニムショートパンツ。ホワイトの色合いで、フィット感のあるシルエットに仕上げたハイウエストスタイル。コットンのリジッドデニムを使用、ダメージ感のあるディテールとローエッジ仕上げの裾が目を引くアイテム。','gender' => 'ウィメンズ'], 
            ['name' => "プリントショートパンツ",'price' => 42900,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのスウェットショートパンツ。グレー/パープルの色合いで、ヒートリアクティブ薄手ジャージーコットンを使用。フロントに施したプリントがポイント。伸縮性のあるウエストバンドとサイドポケットを配したデザイン。レギュラー丈、リラックスフィットのユニセックススタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ストライプショーツ",'price' => 37400,'category_id' => 6,'release_date' => new DateTime(),'detail' => 'Usen Studiosのスウェットショートパンツ。全体にオレンジマルチのストライプパターンをあしらったコットンのリブ編みジャカードを使用。フロントにあしらったFaceロゴパッチと、バックポケットに施したFaceロゴ刺繍がアクセントに。ウエストはドローコード入りの伸縮性のあるデザイン。サイドポケットとバックポケット付き。レギュラーフィットのユニセックススタイル。','gender' => 'ウィメンズ'], 


            ['name' => "テーラードフレアートラウザーズ ",'price' => 70400,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのブラックトラウザーズ。ウールブレンド素材を使用。トップステッチを施したフロントのレッグプリーツとロールアップヘムがポイント。サイドポケットとバックウェルトポケット付き。ミッドウエスト、フレアレッグ、丈が長めのレギュラーフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "リラックスフィットプリントトラウザーズ ",'price' => 73700,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのトラウザーズ。光沢仕上げを施したライトブラウンのベルベットを使用。全体にプリント入り、ファイブポケットデザイン。ハイウエスト、ワイドレッグ、丈が長めのリラックスフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "テーラードトラウザーズ",'price' => 75900,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのテーラードトラウザーズ。ライトサンドの色合いで、トップステッチを施したレッグプリーツとロールアップヘムがポイント。リネン＆コットンブレンド素材を使用。前後にポケット付き。ローライズウエスト、長めの丈に仕上げたリラックスフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "リネンブレンドトラウザーズ ",'price' => 64900,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのテーラードトラウザーズ。クリームホワイトのリネンブレンド素材を使用。レッグプリーツのディテール、サイドポケットとジェッテッドバックポケット付き。ローライズウエスト、長めの丈に仕上げたレギュラーフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "テーラード ラップトラウザーズ ",'price' => 85800,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのスーツトラウザーズ。グレーのウールブレンド素材を使用。レッグプリーツのディテールを施したラップスタイル。サイドとバックに機能的なポケット付き。丈が長めのリラックスフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "テーラード フレアートラウザーズ",'price' => 70400,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのトラウザーズ。チェスナットブラウンのウールブレンド素材を使用。トップステッチを施したフロントのレッグプリーツとロールアップヘムがポイント。サイドポケットとバックウェルトポケット付き。ミッドウエスト、フレアレッグ、丈が長めのレギュラーフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ナロー テーラードトラウザーズ",'price' => 61600,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのテーラードトラウザーズ。ブラックのウールブレンド素材を使用。フロントにアングルポケット、バックにボタン付きジェッテッドポケット付き。ミッドウエスト、ナローレッグ、丈が長めのナローフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "ナロー テーラードトラウザーズ",'price' => 61600,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのテーラードトラウザーズ。シーウィードグリーンのウールブレンド素材を使用。フロントにアングルポケット、バックにボタン付きジェッテッドポケット付き。ミッドウエスト、ナローレッグ、丈が長めのナローフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "リラックス ドローストリングトラウザーズ",'price' => 64900,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのトラウザーズ。ウォームホワイトのコットン＆リネンブレンド素材を使用。伸縮性のあるウエストバンドとヘムにドローストリングを配したデザイン。ローエッジ仕上げ。膝部分はプリーツを施したゆとりのある仕上がり。ミッドウエスト、ワイドレッグ、丈が長めのリラックスフィットスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "フィット フレアトラウザーズ ",'price' => 73700,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのトラウザーズ。ペールグリーンマルチの色合いで、光沢仕上げを施したドレープ感のある風合いとマルチトーンデザインがポイント。フロントにコンシールボタン留め、バックにジェッテッドポケット付き。ミッドウエスト、フレアレッグ、丈が長めのフィット感のあるスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "プリント フレアトラウザーズ",'price' => 73700,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのトラウザーズ。ドレープ感のあるグリーンマルチのテクスチャードクレープ素材を使用。全体にあしらったプリントがポイント。コンシールボタン留め、バックにデコラティブなポケット付き。ミッドウエスト、フレアレッグ、丈が長めのフィット感のあるスタイル。','gender' => 'ウィメンズ'], 
            ['name' => "テーラードトラウザーズ",'price' => 70400,'category_id' => 7,'release_date' => new DateTime(),'detail' => 'Usen Studiosのテーラードトラウザーズ。全体にライトブルー/ピンクのギンガムパターンをあしらったリネンブレンド素材を使用。サイドポケットとバックポケット付き。ローライズ、フレアーレッグ、丈が長めのレギュラーフィットスタイル。','gender' => 'ウィメンズ'], 

           
        ]);
    }
}
